Admin properties:
  Name: "FakeAdmin"
  Ip: "SPECTER" # this can be anything
  Port: "19133" # this can be any real port number
  # If the server has any authentication systems
  authentication:
    plugin: ""
    password: "password"
  invisible-to-non-op: false
