Admin properties:
  Name: "FakeAdmin"
  Ip: "127.0.0.1" # this can be anything
  Port: "58383" # this can be any real port number
  # If the server has any authentication systems
  authentication:
    plugin: "HereAuth"
    password: "password"
  invisible to non op: false
  reply to messages: false
    command: true
    chat: true
  Fake Hacks: false